spring.application.name=porfoliomanagment
server.port=8080
server.ssl.enabled=false
scraper.base-url=https://www.sharesansar.com/today-share-price
spring.session.store-type=none

# application.properties
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

# Nepse Database Configuration
spring.datasource.nepse.jdbc-url=jdbc:mysql://localhost:3306/porfoliomanagment_nepse?createDatabaseIfNotExist=true
spring.datasource.nepse.username=root
spring.datasource.nepse.password=
spring.datasource.nepse.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.nepse.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.nepse.jpa.show-sql=true

# Portfolio Database Configuration
spring.datasource.portfolio.jdbc-url=jdbc:mysql://localhost:3306/porfoliomanagment_detail?createDatabaseIfNotExist=true
spring.datasource.portfolio.username=root
spring.datasource.portfolio.password=
spring.datasource.portfolio.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.portfolio.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.portfolio.jpa.show-sql=false

lstm.version=v4
lstm.hidden-size=64
lstm.dense-size=4
lstm.input-size=18
lstm.output-size=1
lstm.epochs=10
lstm.batch-size=32
lstm.training-rate=0.001
lstm.threshold=1.0
lstm.retrain-threshold-days=365
lstm.early-stopping-enabled=false
lstm.autosave-enabled=false
lstm.autosave-online=false
lstm.save-min-interval-ms=600000

lstm.base-dir=src/main/resources/static/model